name: build

on:
  push:
    tags:
      - 'v*' # Build tagged releases

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux-amd64:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release

          # Rename file and compress it
          mv target/release/horsegen horsegen-${GITHUB_REF#refs/tags/v}-linux-amd64
          bzip2 -f horsegen-${GITHUB_REF#refs/tags/v}-linux-amd64

      - name: Upload Linux release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: horsegen-*-linux-amd64.bz2

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        run: |
          cargo build --release

          # Rename file and compress it
          mv target/release/horsegen horsegen-${GITHUB_REF#refs/tags/v}-macOS
          bzip2 -f horsegen-${GITHUB_REF#refs/tags/v}-macOS

      - name: Upload macOS release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: horsegen-*-macOS.bz2
